name: Markdown Lint
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - name: Run MarkdownLint
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: '**/*.md'
