name: Markdown Link Check
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '**/*.md'

jobs:
  md-check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Vérifier les liens Markdown
        uses: YakDriver/md-check-links@latest
        with:
          quiet: 'yes'
          verbose: 'yes'
          directory: '.'
          extension: '.md'
