name: Markdown Lint

on:
  push:
    paths:
      - '**/*.md'
      - '*.md'
  pull_request:
    paths:
      - '**/*.md'
      - '*.md'

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: '**/*.md'

