name: Markdown Link Check
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '**/*.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: tcort/github-action-markdown-link-check@v1